### ISSUE TITLE
Add vec_to_first and vec_to_last aggregates.

### ISSUE THREAD

**Issue by msqr** [pjungwir/aggs_for_vecs#11]
I discovered another set of aggregates that would be useful to me: `vec_to_first` and `vec_to_last`. These return an array containing the first/last non-null values seen in the input arrays, per position. They are expected to be used with an `ORDER BY` clause, e.g. 

```sql
SELECT vec_to_first(data_a ORDER BY ts)
FROM measurements2
```

I have implemented these in a [feature/accum-firstlast](https://github.com/SolarNetwork/aggs_for_vecs/tree/feature/accum-firstlast) and included tests, and the functions work with any element type (not just numbers).  I've built off the [feature/accum-cached-fcinfo](https://github.com/SolarNetwork/aggs_for_vecs/tree/feature/accum-cached-fcinfo) branch as discussed in #10, but does not depend on those changes so could be included without if needed (although I'd prefer to include those as well!).

**Comment by pjungwir** [comment]
Those sound like they'd be handy! I don't mind whether you build them on
top of the other work or not.

**Comment by pjungwir** [comment]
Completed by #13.
