### ISSUE TITLE
[QUESTION] Does this extension benefit from having an index of any type?

### ISSUE THREAD

**Issue by ibrykov-mdsol** [pjungwir/aggs_for_vecs#16]
Thank you for this extension!

It's not mentioned in the docs in any shape or form, hence this issue.

Should we expect better performance on properly indexed array columns? If so, which type of indexing is preferred?

**Comment by pjungwir** [comment]
Hi, thanks for your interest in this extension!

This extension speeds math on arrays (in particular when you treat them as vectors, e.g. `[1,2,3] + [2,2,2] = [3,4,5]`). But it doesn't change the planner or do anything to improve loading them off disk.

If you are selecting rows based on your arrays, then a GIN index might help (depending on the specifics), but you don't need this extension for that, and this extension won't make it any faster.

**Comment by ibrykov-mdsol** [comment]
Thank you! This makes sense.
