### ISSUE TITLE
Code does not compile with Postgresql 16

### ISSUE THREAD

**Issue by viktorras** [pjungwir/aggs_for_vecs#17]
Trying to run make with Postgresql 16 headers gives this error
./vec_to_var_samp.c:212:53: error: incompatible integer to pointer conversion passing 'Datum' (aka 'unsigned long') to parameter of type 'Numeric' (aka 'struct NumericData *') [-Wint-conversion]

The problem is with the last commit in vec_to_var_samp.c

Probably the problem can be fixed by changing
state->state.dvalues[i] = NumericGetDatum(NUMERIC_ZERO);
to 
state->state.dvalues[i] = NUMERIC_ZERO;
in line 212

**Comment by pjungwir** [comment]
You're right! Fixed on master.
