### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by yrashk** [pjungwir/aggs_for_vecs#20]
Hi Paul,

I am preparing to package your extensions on [postgres.pm](http://postgres.pm/) – would it be possible to tag releases in this repo? This makes it so much easier to pick up releases automatically.

(I see that you've tagged _one_ release in the repo, but not others.)

**Comment by pjungwir** [comment]
Oh yes, I should be doing that. I tagged the last few versions. Let me know if you need more.

**Comment by yrashk** [comment]
Thank you!
