### ISSUE TITLE
Possible to use existing Postgres aggregate functions like numeric_avg_accum, towards two-step aggregation

### ISSUE THREAD

**Issue by msqr** [pjungwir/aggs_for_vecs#8]
Having now worked a little bit with the Postgres code to support `NUMERIC`, I noticed that internally Postgres provides a [great set of functions](https://github.com/postgres/postgres/blob/e54a758d24dab056bb7f50d26c57a3c8761cc44a/src/backend/utils/adt/numeric.c) for aggregating the `NUMERIC` type. For example, the [`avg(numeric)` definition](https://github.com/postgres/postgres/blob/def5b065ff22a16a80084587613599fe15627213/src/include/catalog/pg_aggregate.dat#L32-L39) has:

```
{ aggfnoid => 'avg(numeric)', aggtransfn => 'numeric_avg_accum',
  aggfinalfn => 'numeric_avg', aggcombinefn => 'numeric_avg_combine',
  aggserialfn => 'numeric_avg_serialize',
  aggdeserialfn => 'numeric_avg_deserialize',
  aggmtransfn => 'numeric_avg_accum', aggminvtransfn => 'numeric_accum_inv',
  aggmfinalfn => 'numeric_avg', aggtranstype => 'internal',
  aggtransspace => '128', aggmtranstype => 'internal',
  aggmtransspace => '128' },
```

Internally the aggregates make use of state objects like [`NumericAggState`](https://github.com/postgres/postgres/blob/e54a758d24dab056bb7f50d26c57a3c8761cc44a/src/backend/utils/adt/numeric.c#L4590-L4603). That same state object is shared between many of Postgres' aggregate functions, and (apparently) the optimizer knows that something like

```sql
SELECT count(numeric), sum(numeric), avg(numeric) FROM table_of_numerics
```

can accumulate/calulcate the `NumericAggState` once for all three aggregates, and then just execute different final functions on that shared state to produce the desired count, sum, and average results.

I was thinking this approach would be really great applied here, on arrays of numbers, and the performance benefit could be substantial. I also use the Timescale extension, and they are working on a set of [two-step aggregates](https://github.com/timescale/timescaledb-toolkit/blob/main/docs/two-step_aggregation.md) that work great on single-value columns, but as I am working with array columns I want the same sort of result applied like this extension would, as vectors.

That all leads me to my first question: would it be possible/advisable to try to re-use the existing Postgres functions like `numeric_avg_accum`, but passing them elements of our input array and storing their result state in this extension's `vecvalues` array. Here's what I'm trying to express, in pseudo code:

```c
typedef union pgnum {
  int16 i16;
  int32 i32;
  int64 i64;
  float4 f4;
  float8 f8;
  Datum datum; // to store the value returned from something like numeric_avg_accum
} pgnum;

Datum
vec_to_numeric_avg_accum(PG_FUNCTION_ARGS)
{
  // skipping a bunch of declarations
  get_typlenbyvalalign(elemTypeId, &elemTypeWidth, &elemTypeByValue, &elemTypeAlignmentCode);
  deconstruct_array(currentArray, elemTypeId, elemTypeWidth, elemTypeByValue, elemTypeAlignmentCode,
      &currentVals, &currentNulls, &currentLength);
  for (i = 0; i < arrayLength; i++) {
    if (currentNulls[i]) {
      // do nothing: nulls can't change the result.
    } else {
      if (state->state.dnulls[i]) {
        state->state.dnulls[i] = false;
      }
      // forward our invocation to the numeric_avg_accum function, changing the passed value argument from
      // our array argument to the array element at index i
      state->vecvalues[i].datum = DirectFunctionCall2(numeric_avg_accum, state->vecvalues[i].datum, currentVals[i]);
    }
  }
  PG_RETURN_POINTER(state);
}
```

I tried to hack something together to see if this works, but it does not, reporting the error `ERROR:  aggregate function called in non-aggregate context`. I think I understand why that happens: I'm calling `DirectFunctionCall2` which will create a new `FunctionCallInfo` structure that does not include the same settings as the one passed to `vec_to_numeric_avg_accum`, especially whatever part that makes the `AggCheckCallContext()` call succeed.

Would it be possible to essentially create a copy of the `FunctionCallInfo` passed to `vec_to_numeric_avg_accum` but with the array argument swapped to an element of that array, and pass that to the `numeric_avg_accum` somehow, maybe via [`FunctionCallInvoke`](https://github.com/postgres/postgres/blob/def5b065ff22a16a80084587613599fe15627213/src/include/fmgr.h#L160-L172)?

**Comment by pjungwir** [comment]
> the optimizer . . . can accumulate/calulcate the `NumericAggState` once for all three aggregates

That is a cool trick! I can't find any notes about it in the documentation or source code though. Can you send me a reference where you're reading that?

> Would it be possible to essentially create a copy of the `FunctionCallInfo`

This seems like it should be possible. It makes me a bit uneasy though. It seems like something that could easily break between Postgres versions. But if it is really a big performance boost, it might still be worth it. I'd be happy to at least see an experiment taking that approach.

If you're interested in speeding up these functions, making them support [partial aggregation](https://www.postgresql.org/docs/14/xaggr.html#XAGGR-PARTIAL-AGGREGATES) would probably have a big payoff, and that would stay within something officially supported.

A few years ago I also experimented with SIMD instructions, and in my rough benchmarks it was roughly halving the time. I just never got around to implementing all the functions. I don't think we could do that for `NUMERIC` though since we rely on Postgres's own arithmetic functions.

**Comment by msqr** [comment]
> the optimizer . . . can accumulate/calulcate the NumericAggState once for all three aggregates

I was actually only basing that statement on what the Timescale folks wrote, [here](https://github.com/timescale/timescaledb-toolkit/blob/e46e98e65ad5e3f70f6560d6146d2a0e7e8401f9/docs/two-step_aggregation.md#accessor-functions-with-additional-parameters-). I don't actually know how that translates to the code, I made a guess that the `NumericAggState` structure was used because I saw that being used in aggregate functions like [numeric_avg_accum](https://github.com/postgres/postgres/blob/e54a758d24dab056bb7f50d26c57a3c8761cc44a/src/backend/utils/adt/numeric.c#L4908-L4910).

I was thinking partial aggregation was a slightly different optimization that what I was thinking of, and both could be applied! Am I correct in understanding that partial aggregation would allow parallel workers to compute a subset of the aggregation, followed by a combining function to merge all the worker results into one final result? So what I'd like to do is more optimize the time spent computing multiple aggregates on the same input data set. In my use case, I want to calculate the average, min, max, count, and sum for sets of data. Here's an example query (it uses the Timescale time_bucket() function):

```sql
SELECT 
	  time_bucket('5 minutes'::interval, d.ts) AS ts_start
	, vec_to_mean(d.data_i) AS data_i
	, vec_to_count(d.data_i) AS count_i
	, vec_to_min(d.data_i) AS min_i
	, vec_to_max(d.data_i) AS max_i
FROM d
GROUP BY time_bucket('5 minutes'::interval, d.ts)
```
What I was hoping to be able to do was something like this:

```sql
SELECT 
	  time_bucket('5 minutes'::interval, d.ts) AS ts_start
	, vec_to_mean(vec_stat_calc(d.data_i)) AS data_i
	, vec_to_count(vec_stat_calc(d.data_i)) AS count_i
	, vec_to_min(vec_stat_calc(d.data_i)) AS min_i
	, vec_to_max(vec_stat_calc(d.data_i)) AS max_i
FROM d
GROUP BY time_bucket('5 minutes'::interval, d.ts)
```

with the hope that the optimizer would be smart enough to execute `vec_stat_calc(d.data_i)` once into something like a `VecNumericAggState` aggregate state structure, and then all the `vec_to_X()` functions turn into "simple" accessors for that aggregate out of the shared state. The `VecNumericAggState` could support all numeric data types, like what the `pgnum` union provides.

> This seems like it should be possible. It makes me a bit uneasy though. It seems like something that could easily break between Postgres versions. But if it is really a big performance boost, it might still be worth it. I'd be happy to at least see an experiment taking that approach.

I wondered about that. I thought the things in `fmgr.h` like `fmgr_info_copy()` or `InitFunctionCallInfoData` followed by `FunctionCallInvoke` would be fairly stable APIs (if those are even appropriate here, I'm make a lot of guesses as I'm inexperienced in this stuff).

**Comment by pjungwir** [comment]
Ah, I read the Timestamp article you linked before, but it didn't click that you could do the same thing in stock Postgres. That's cool!

Yes, the optimizer can identify repeated expressions and re-use the results. For example this will only call `vec_to_max` once:

```
select vec_to_max(nums), (vec_to_max(nums))[1], array_length(vec_to_max(nums), 1) from measurements;
```

I like that idea of exposing an aggregate accumulator function and then separate accessor functions to pull off the results. You'll have to define a custom type I believe, but I don't think it will need much user-facing stuff.

I'd like to still keep the simple versions of our `vec_to_foo` functions, so that people don't need to do the two-step thing if they don't want to. But having a two-step option would be really cool.

**Comment by pjungwir** [comment]
Oh I meant to add: you're probably right about fmgr being pretty stable.

**Comment by pjungwir** [comment]
> Am I correct in understanding that partial aggregation would allow parallel workers to compute a subset of the aggregation, followed by a combining function to merge all the worker results into one final result?

Exactly!

**Comment by msqr** [comment]
OK! So the two-step aggregate is in some ways separate from trying to re-use those `numeric_*` functions as originally outlined in this issue. I could try to implement a two-step aggregate out of the existing code, it's just that in the `NUMERIC` case there is so much already sitting there in Postgres, I thought it would be most excellent to re-use it. Do you have any tips/pointers on using the things in `fmgr.h` to make the sort of lower-level calls I'm trying to do?

**Comment by msqr** [comment]
I've been trying to [hack my way into understanding how to make this work](https://github.com/SolarNetwork/aggs_for_vecs/blob/68a464593adcc1b712120f71ced693a49c6996be/vec_to_mean_numeric.c). At this point, I'm able to [look up `numeric_avg_accum` function ](https://github.com/SolarNetwork/aggs_for_vecs/blob/68a464593adcc1b712120f71ced693a49c6996be/vec_to_mean_numeric.c#L59)and I think I'm [invoking it ](https://github.com/SolarNetwork/aggs_for_vecs/blob/68a464593adcc1b712120f71ced693a49c6996be/vec_to_mean_numeric.c#L97)once per array element, saving the returned state value and passing it back each time.

Then in the final function I [look up the `numeric_avg` function](https://github.com/SolarNetwork/aggs_for_vecs/blob/68a464593adcc1b712120f71ced693a49c6996be/vec_to_mean_numeric.c#L132) and [invoke it](https://github.com/SolarNetwork/aggs_for_vecs/blob/68a464593adcc1b712120f71ced693a49c6996be/vec_to_mean_numeric.c#L152-L155), but it is returning `NULL` and I haven't been able to figure out why.

Here's what I get when I try to use the `vec_to_mean` function, with all my excessive logging:

```
SELECT vec_to_mean(nums) FROM measurements WHERE sensor_id IN (5,6);

NOTICE:  cached numeric_avg_accum FmgrInfo
NOTICE:  allocated vec_accum_fcinfo memory 64
NOTICE:  init vec_accum_fcinfo struct
NOTICE:  invoking trans 0
NOTICE:  invoking trans 1
NOTICE:  invoking trans 2
NOTICE:  invoking trans 0
NOTICE:  invoking trans 1
NOTICE:  invoking trans 2
NOTICE:  about to do create proxy_fcinfo
NOTICE:  created proxy_fcinfo
NOTICE:  init proxy_fcinfo
NOTICE:  invoking final 0
ERROR:  numeric_avg returned NULL
```

I've been stuck on this for a while now, maybe you have an idea what's going wrong?

**Comment by pjungwir** [comment]
I took a look through your code & the built-in functions you're using. I didn't see anything obvious. But since `numeric_avg` does this . . .

```

    /* If there were no non-null inputs, return NULL */
    if (state == NULL || NA_TOTAL_COUNT(state) == 0)
        PG_RETURN_NULL();
```

I think I'd start with inspecting the state before you call it to make sure `NA_TOTAL_COUNT` is not zero.

I don't think I'll have a chance to look more closely until the weekend. One thing you could do is build Postgres from source then install the extension against it so you can add debugging calls to the Postgres functions too.

**Comment by msqr** [comment]
Ah, I needed a break to get my head cleared to see the logic bug I fixed in SolarNetwork/aggs_for_vecs@0a84ca5de24c22962994c5b1ced337919a212881. After that, the function runs. I did take your advice and locally build Postgres and learn how to debug it, so that was a nice learning experience and quite interesting to step through the code. Now I can clean the code up and do some actual testing!

**Comment by msqr** [comment]
I've cleaned up the code a bit in the latest [feature/numeric-stats-agg](https://github.com/SolarNetwork/aggs_for_vecs/tree/feature/numeric-stats-agg) and the function is still not quite right because of some memory handling issue I haven't been able to figure out yet. The function will eventually crash after a few invocations, and looking in the debugger it looks like some memory addresses are invalid.

**Comment by pjungwir** [comment]
Ha ha I stared and stared at that line and never saw the problem. :-) It sounds like you're making some great progress!

**Comment by msqr** [comment]
OK, I was able to fix the bugs and get everything working in [feature/numeric-stats-agg](https://github.com/SolarNetwork/aggs_for_vecs/tree/feature/numeric-stats-agg). I think I should start over in a new branch, however, so the original single-step implementation remains as-is, and I can work on two-step aggregation to really get the most benefit out of this approach. I'll close this issue as I think its served its (exploratory) purpose now.
